import 'package:hive/hive.dart';

part 'all_azkar_model.g.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
@HiveType(typeId: 1)
class AzkarModel extends HiveObject {
/*
{
  "id": 1,
  "text": "أَعُوذُ بِاللَّهِ مِنَ الشَّيطَانِ الرَّجِيمِ ﴿اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَوَاتِ وَالْأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾.",
  "count": 1,
  "audio": "/audio/75.mp3",
  "filename": "75"
}
*/
  @HiveField(0)
  int? id;
  @HiveField(1)
  String? text;
  @HiveField(2)
  int? count;
  @HiveField(3)
  String? audio;
  @HiveField(4)
  String? filename;

  AzkarModel({
    this.id,
    this.text,
    this.count,
    this.audio,
    this.filename,
  });

  AzkarModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    text = json['text']?.toString();
    count = json['count']?.toInt();
    audio = json['audio']?.toString();
    filename = json['filename']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['text'] = text;
    data['count'] = count;
    data['audio'] = audio;
    data['filename'] = filename;
    return data;
  }
}

@HiveType(typeId: 0)
class AllAzkarModel  extends HiveObject{
/*
{
  "id": 1,
  "category": "أذكار الصباح والمساء",
  "audio": "/audio/ar_7esn_AlMoslem_by_Doors_028.mp3",
  "filename": "ar_7esn_AlMoslem_by_Doors_028",
  "array": [
    {
      "id": 1,
      "text": "أَعُوذُ بِاللَّهِ مِنَ الشَّيطَانِ الرَّجِيمِ ﴿اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَوَاتِ وَالْأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ﴾.",
      "count": 1,
      "audio": "/audio/75.mp3",
      "filename": "75"
    }
  ]
}
*/
  @HiveField(0)
  int? id;
  @HiveField(1)
  String? category;
  @HiveField(2)
  String? audio;
  @HiveField(3)
  String? filename;
  @HiveField(4)
  List<AzkarModel?>? array;

  AllAzkarModel({
    this.id,
    this.category,
    this.audio,
    this.filename,
    this.array,
  });

  AllAzkarModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    category = json['category']?.toString();
    audio = json['audio']?.toString();
    filename = json['filename']?.toString();
    if (json['array'] != null) {
      final v = json['array'];
      final arr0 = <AzkarModel>[];
      v.forEach((v) {
        arr0.add(AzkarModel.fromJson(v));
      });
      array = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['category'] = category;
    data['audio'] = audio;
    data['filename'] = filename;
    if (array != null) {
      final v = array;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['array'] = arr0;
    }
    return data;
  }
}
